// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerioperativeAssistant.Data;

#nullable disable

namespace PerioperativeAssistant.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260918180150_ResourceForecastingDomainModel")]
    partial class ResourceForecastingDomainModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PerioperativeAssistant.Models.ResourceInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MinimumDesiredQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<int>("UnavailableQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceTypeId", "Location")
                        .IsUnique();

                    b.ToTable("ResourceInventories");
                });

            modelBuilder.Entity("PerioperativeAssistant.Models.ResourcePrediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ExpectedQuantity")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("bit");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PredictedUseTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Probability")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SurgicalCaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredictedUseTime");

                    b.HasIndex("SurgicalCaseId");

                    b.HasIndex("ResourceTypeId", "PredictedUseTime");

                    b.ToTable("ResourcePredictions");
                });

            modelBuilder.Entity("PerioperativeAssistant.Models.ResourceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConsumable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReusable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiresReprocessing")
                        .HasColumnType("bit");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Variant")
                        .IsUnique();

                    b.ToTable("ResourceTypes");
                });

            modelBuilder.Entity("PerioperativeAssistant.Models.ResourceUseEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AvailableAgainAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BecameUnavailableAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ProcessingCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessingStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuantityUsed")
                        .HasColumnType("int");

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentToProcessingAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SurgicalCaseId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalTurnaroundMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SurgicalCaseId");

                    b.HasIndex("UsedAt");

                    b.HasIndex("ResourceTypeId", "AvailableAgainAt");

                    b.HasIndex("ResourceTypeId", "UsedAt");

                    b.ToTable("ResourceUseEvents");
                });

            modelBuilder.Entity("PerioperativeAssistant.Models.SurgicalCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualDurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("AnesthesiaType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProcedureCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProcedureCodeSystem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProcedureType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ScheduledDurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.HasIndex("Location");

                    b.HasIndex("ScheduledStart");

                    b.HasIndex("Service");

                    b.ToTable("SurgicalCases");
                });

            modelBuilder.Entity("PerioperativeAssistant.Models.ResourceInventory", b =>
                {
                    b.HasOne("PerioperativeAssistant.Models.ResourceType", "ResourceType")
                        .WithMany("ResourceInventories")
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("PerioperativeAssistant.Models.ResourcePrediction", b =>
                {
                    b.HasOne("PerioperativeAssistant.Models.ResourceType", "ResourceType")
                        .WithMany("ResourcePredictions")
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PerioperativeAssistant.Models.SurgicalCase", "SurgicalCase")
                        .WithMany("ResourcePredictions")
                        .HasForeignKey("SurgicalCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceType");

                    b.Navigation("SurgicalCase");
                });

            modelBuilder.Entity("PerioperativeAssistant.Models.ResourceUseEvent", b =>
                {
                    b.HasOne("PerioperativeAssistant.Models.ResourceType", "ResourceType")
                        .WithMany("ResourceUseEvents")
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PerioperativeAssistant.Models.SurgicalCase", "SurgicalCase")
                        .WithMany("ResourceUseEvents")
                        .HasForeignKey("SurgicalCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceType");

                    b.Navigation("SurgicalCase");
                });

            modelBuilder.Entity("PerioperativeAssistant.Models.ResourceType", b =>
                {
                    b.Navigation("ResourceInventories");

                    b.Navigation("ResourcePredictions");

                    b.Navigation("ResourceUseEvents");
                });

            modelBuilder.Entity("PerioperativeAssistant.Models.SurgicalCase", b =>
                {
                    b.Navigation("ResourcePredictions");

                    b.Navigation("ResourceUseEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
